"""Initial migration

Revision ID: ee276bbf6b61
Revises: b46a1af886eb
Create Date: 2025-12-14 22:06:05.532853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee276bbf6b61'
down_revision = 'b46a1af886eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nom', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['prenom'])
        batch_op.create_unique_constraint(None, ['adress'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_creation')
        batch_op.drop_column('email')
        batch_op.drop_column('telephone')
        batch_op.drop_column('adress')
        batch_op.drop_column('nom')
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
